import { Item } from "./types"

export const VALUES: Item[] = [
  
  {
    id: "1",
    glitchedOff: true,
    cursedOff: true,
    name: "Bling Freddy",
    image: "/Skins/Bling.webp",
    tier: "exclusive",
    value: 95,
    ac: 764,
    era: "Summer upd 2025",
    releaseDate: "04/14/2025",
    skills: [
      { name: "Springlocked", description: "ez win" },
      { name: "Freddys thing ", description: "ez win" }
    ],
    demand: "moderate",
    updates: ["Now able to use sprnglocked"],
    supply: 500
  },
  {
    id: "2",
    glitchedOff: true,
    cursedOff: true,
    name: "Springtrap 2026",
    image: "/Skins/Springtrap2026.webp",
    tier: "sacred",
    value: 215,
    ac: 180,
    era: "New years",
    releaseDate: "???",
    skills: [
      { name: "Spring Lock", description: "ez win" }
    ],
    demand: "extreme",
    supply: 181
  },
  {
    cursedOff: true,
    id: "3",
    name: "Nightmare Tidal King",
    image: "/Skins/Tidal.webp",
    tier: "sacred",
    value: 110,
    ac: 724,
    era: "Summer 2025",
    releaseDate: "???",
    skills: [
      { name: "Tidal Wave", description: "wave of baby oil" },
    ],
    demand: "extreme",
    updates: ["New vfx better ones coming soon"],
    glitchedVal: 1600,
    glitchedAC: 6,
    supply: 724

  },
  {
    cursedOff: true,
    id: "4",
    name: "Dragon MXES",
    image: "/Skins/DragonMXES.webp",
    tier: "sacred",
    value: 65,
    ac: 300,
    era: "Lunar New Years",
    releaseDate: "???",
    skills: [
      { name: "Dragon Breath", description: "Releases racchet stank breath" },
    ],
    demand: "moderate",
    updates: ["ability still broken"],
    glitchedVal: 925,
    glitchedAC: 4,
    supply: 300
  },
  {
    cursedOff: true,
    id: "5",
    name: "Midnight Motorist",
    image: "/Skins/MidnightMotorist.webp",
    tier: "sacred",
    value: 60,
    ac: 790,
    era: "Halloween",
    releaseDate: "????",
    skills: [
      { name: "Vengance", description: "buns ability " },

    ],
    demand: "high",
    updates: ["gc mm got created but got reversed"],
    glitchedVal: 1100,
    glitchedAC: 10,
    supply: 790
  },
  {
    cursedOff: true,
    id: "6",
    name: "Bloomtrap",
    image: "/Skins/Bloomtrap.webp",
    tier: "secret",
    value: 60,
    ac: 216,
    era: "Easter",
    releaseDate: "04/04/2026",
    skills: [
      { name: "Springlocked", description: "ez win" },
      { name: "Gardeners grasp", description: "dumbass ability" },

    ],
    demand: "high",
    updates: ["can now get spirnglocked"],
    glitchedVal: 800,
    glitchedAC: 3,
    supply: 316

  },
  {
    cursedOff: true,
    id: "7",
    name: "Clowntrap",
    image: "/Skins/Clowntrap.webp",
    tier: "sacred",
    value: 50,
    ac: 281,
    era: "Halloween 2025",
    releaseDate: "???",
    skills: [
      { name: "springlocked", description: "ez win" },

    ],
    demand: "trending",
    updates: ["Sudden rise in demand"],
    glitchedVal: 70,
    glitchedAC: 97,
    supply: 281
  },
  {
    cursedOff: true,
    id: "8",
    name: "Mad Hatter Vanny",
    image: "/Skins/Mad-Hatter-Vanny.webp",
    tier: "sacred",
    value: 40,
    ac: 488,
    era: "Easter",
    releaseDate: "04/04/2026",
    skills: [
      { name: "Rabbits calling", description: "worse sha" },
    ],
    demand: "decent",
    updates: ["dumbass zero has g #8 now "],
    glitchedVal: 450,
    glitchedAC: 8,
    supply: 488
  },
  {
    cursedOff: true,
    id: "9",
    name: "Lava ennard",
    image: "/Skins/LavaEnnard.webp",
    tier: "sacred",
    value: 35,
    ac: 525,
    era: "TJOC",
    releaseDate: "???",
    skills: [
      { name: "Limb GRIPPER", description: "grip those limbs boi" },
    ],
    demand: "moderate",
    updates: ["new vfx"],
    glitchedVal: 425,
    glitchedAC: 1,
    supply: 525
  },
  {
    cursedOff: true,
    id: "10",
    name: "Withered moon rose",
    image: "/Skins/Withered-Moon-Rose.webp",
    tier: "sacred",
    value: 30,
    ac: 582,
    era: "Valentines",
    releaseDate: "???",
    skills: [
      { name: "fuckass moon ability", description: "worse than ampt im crine" },
    ],
    demand: "decent",
    glitchedVal: 325,
    glitchedAC: 5,
    supply: 582
  },
  {
    id: "11",
    name: "Crimson Ballora",
    image: "/Skins/CrimsonBallora.webp",
    tier: "mythic",
    value: 25,
    ac: 1096,
    era: "Lunar New Year",
    releaseDate: "???",
    skills: [
      { name: "fuckass fan", description: "35 free dmg with a decent cd" },
    ],
    demand: "high",
    glitchedVal: 300,
    updates: ["ability got nerfed"],
    glitchedAC: 20,
    gcVal: 600,
    gcAC: 1,
    supply: 1096
  },
  {
    cursedOff: true,
    id: "12",
    name: "The Pumpkin Rabbit",
    image: "/Skins/ThePumpkinRabbit.webp",
    tier: "sacred",
    value: 17,
    ac: 803
,
    era: "Walten Files",
    releaseDate: "???",
    skills: [
      { name: "shadow clone", description: "shadow clone n shi" },
    ],
    demand: "decent",
    glitchedVal: 150,
    glitchedAC: 8,
    supply: 803

  },
  {
    glitchedOff: true,
    cursedOff: true,
    id: "13",
    name: "8-bit",
    image: "/Skins/8-bit.webp",
    tier: "sacred",
    value: 20,
    ac: 556,
    era: "I dont fucking know son",
    releaseDate: "???",
    skills: [
      { name: "vengance", description: "L ability" },
    ],
    demand: "none",
    supply: 500
  },
  {
    cursedOff: true,
    id: "14",
    name: "Blooming ennard",
    image: "/Skins/BloomingEnnard.webp",
    tier: "sacred",
    value: 15,
    ac: 673,
    era: "Easter",
    releaseDate: "???",
    skills: [
      { name: "limb gripper(vegan edition)", description: "free win(no animals were harmed in the making of this skill)" },
    ],
    demand: "moderate",
    supply: 673,
    glitchedVal: 120,
    glitchedAC: 10
  },
  {
    id: "15",
    name: "sun-kissed-drop",
    image: "/Skins/SunKissedDrop.webp",
    tier: "sacred",
    value: 11,
    ac: 2686,
    era: "Valentines",
    releaseDate: "???",
    skills: [
      { name: "kissy kissy drop", description: "the name isnt freaky trust" },
    ],
    demand: "moderate",
    supply: 2000,
    cursedVal: 33,
    cursedAC: 20,
  },
  {
    glitchedOff: true,
    id: "16",
    name: "Snowfall",
    image: "/Skins/SnowfallMoon.webp",
    tier: "sacred",
    value: 8,
    ac: 4216,
    era: "Christmas",
    releaseDate: "???",
    skills: [
      { name: "snowfall", description: "use anything else bro please" },
    ],
    demand: "moderate",
    supply: 4000,
    cursedVal: 22,
    cursedAC: 40,
  },
  {
    id: "17",
    name: "Creation",
    image: "/Skins/Creation.webp",
    tier: "sacred",
    value: 7,
    ac: 6732,
    era: "TJOC",
    releaseDate: "???",
    skills: [
      { name: "crwation thingy", description: "nerfed to hell" },
    ],
    demand: "moderate",
    updates: ["ability got nerfed to hell"],
    supply: 6000,
    glitchedVal: 30,
    glitchedAC: 65,
    cursedVal: 15,
    cursedAC: 340,
    gcVal: 80,
    gcAC: 10
  },
  {
    cursedOff: true,
    id: "18",
    name: "Chicas magic rainbow",
    image: "/Skins/ChicasMagicRainbow.webp",
    tier: "sacred",
    value: 22,
    ac: 493,
    era: "Easter",
    releaseDate: "???",
    skills: [
      { name: "rainbow save thingy", description: "takes 20% longer 4 u to die in ballpits" },
    ],
    demand: "moderate",
    supply: 475,
    glitchedVal: 250,
    glitchedAC: 10,
  },
  {
    cursedOff: true,
    id: "19",
    name: "Blessed Helpy",
    image: "/Skins/BlessedHelpy.webp",
    tier: "sacred",
    value: 20,
    ac: 1040,
    era: "Lunar New Year",
    releaseDate: "???",
    skills: [
      { name: "helping hand", description: "nerfed to hell bust still op" },
    ],
    demand: "trending",
    updates: ["ability got nerfed to hell"],
    supply: 1419,
    glitchedVal: 220,
    glitchedAC: 15,
  },
  {
    id: "20",
    name: "Bullfighter Endo",
    image: "/Skins/BullfighterEndo.webp",
    tier: "exclusive",
    value: 5,
    cursedVal: 18,
    cursedAC: 20,
    ac: 1745,
    era: "???",
    releaseDate: "???",
    demand: "moderate",
},
{   
    glitchedVal: 35,
    glitchedAC: 20,
    id: "21",
    name: "Kitsune Lolbit",
    image: "/Skins/Kitsune.webp",
    tier: "exclusive",
    cursedVal: 10,
    cursedAC: 20,
    value: 3,
    ac: 5652,
    era: "Lunar New Year",
    releaseDate: "???",
    demand: "moderate",
},
{
    id: "22",
    name: "Freedom Freddy",
    image: "/Skins/FreedomFreddy.webp",
    tier: "exclusive",
    value: 4,
    ac: 2786,
    cursedVal: 15,
    cursedAC: 20,
    era: "July 4th",
    releaseDate: "???",
    demand: "moderate",
},
{   
    glitchedVal: 25,
    glitchedAC: 35,
    id: "23",
    name: "Birthday Bash Bonnie",
    image: "/Skins/BirthdayBash.webp",
    tier: "exclusive",
    cursedVal: 7,
    cursedAC: 20,
    value: 2,
    ac: 1320,
    era: "???",
    releaseDate: "???",
    demand: "moderate",
},
{
    id: "24",
    name: "Vocalist Bonnie",
    image: "/Skins/Vocalist.webp",
    tier: "exclusive",
    cursedVal: 10,
    cursedAC: 20,
    value: 3,
    ac: 2790,
    era: "???",
    releaseDate: "???",
    demand: "moderate",
},
{   glitchedVal: 15,
    glitchedAC: 20,
    id: "25",
    name: "Lucky Charm Endo-01",
    image: "/Skins/LuckyCharmEndo01.webp",
    tier: "exclusive",
    value: 1,
    ac: 1501,
    era: "Saint patricks day",
    releaseDate: "???",
    demand: "moderate",
},
{
    id: "26",
    name: "Twisted Bonnie",
    image: "/Skins/TwistedBonnie.webp",
    tier: "exclusive",
    value: 4,
    cursedVal: 15,
    cursedAC: 20,
    ac: 4227,
    era: "???",
    releaseDate: "???",
    demand: "moderate",
},
{   glitchedVal: 15,
    glitchedAC: 20,
    id: "27",
    cursedVal: 5,
    cursedAC: 20,
    name: "Chick Chica",
    image: "/Skins/Chick.png",
    tier: "exclusive",
    value: 1,
    ac: 1450,
    era: "Easter",
    releaseDate: "???",
    demand: "moderate",
},
{
    id: "28",
    cursedVal: 15,
    cursedAC: 20,
    name: "Catrina Chica",
    image: "/Skins/CatrinaChica.webp",
    tier: "exclusive",
    value: 4,
    ac: 1518,
    era: "???",
    releaseDate: "???",
    demand: "moderate",
},
{ 
    glitchedVal: 15,
    glitchedAC: 20,
    id: "29",
    name: "Monarch Baby",
    cursedVal: 3,
    cursedAC: 20,
    image: "/Skins/MonarchBaby.webp",
    tier: "exclusive",
    value: 1,
    ac: 2000,
    era: "summer 2026",
    releaseDate: "???",
    demand: "moderate",
},
{
    id: "30",
    cursedVal: 18,
    cursedAC: 20,
    name: "Lady Chica",
    image: "/Skins/LadyChica.webp",
    tier: "exclusive",
    value: 5,
    ac: 4505,
    era: "???",
    releaseDate: "???",
    demand: "moderate",
},
{
    id: "31",
    cursedVal: 15,
    cursedAC: 20,
    name: "Ringmaster Foxy",
    image: "/Skins/RingMasterFoxy.webp",
    tier: "exclusive",
    value: 4,
    ac: 1262,
    era: "???",
    releaseDate: "???",
    demand: "moderate",
},
{
    id: "32",
    cursedVal: 15,
    cursedAC: 20,
    name: "Glam Chica",
    image: "/Skins/GlamChica.webp",
    tier: "exclusive",
    value: 4,
    ac: 3981,
    era: "???",
    releaseDate: "???",
    demand: "moderate",
},
{   glitchedVal: 15,
    glitchedAC: 20,
    id: "33",
    name: "The Mangle",
    image: "/Skins/The-Mangle.webp",
    tier: "exclusive",
    value: 1,
    cursedVal: 3,
    cursedAC: 20,
    ac: 1318,
    era: "???",
    releaseDate: "???",
    demand: "moderate",
},
{   glitchedVal: 45,
    glitchedAC: 20,
    id: "34",
    name: "Hungry Freddy",
    image: "/Skins/HungryFreddy.webp",
    tier: "exclusive",
    cursedVal: 15,
    cursedAC: 20,
    value: 4,
    ac: 2005,
    era: "April fools 2026",
    releaseDate: "???",
    demand: "moderate",
},
{ 
    glitchedVal: 25,
    glitchedAC: 18,
    id: "35",
    cursedVal: 7,
    cursedAC: 20,
    name: "Trickster Puppet",
    image: "/Skins/TricksterPuppet.webp",
    tier: "exclusive",
    value: 2,
    ac: 2649,
    era: "???",
    releaseDate: "???",
    demand: "moderate",
},
{
    id: "36",
    name: "Captain Foxy",
    image: "/Skins/CaptainFoxy.webp",
    tier: "exclusive",
    value: 4,
    cursedVal: 15,
    cursedAC: 20,
    ac: 2893,
    era: "???",
    releaseDate: "???",
    demand: "moderate",
},
{   glitchedVal: 25,
    glitchedAC: 30,
    id: "37",
    cursedVal: 7,
    cursedAC: 20,
    name: "Sprinting Fredbear",
    image: "/Skins/SprintingFredbear.webp",
    tier: "exclusive",
    value: 2,
    ac: 3378,
    era: "???",
    releaseDate: "???",
    demand: "moderate",
},
{
    id: "38",
    name: "Samurai Foxy",
    image: "/Skins/SamuraiFoxy.webp",
    tier: "exclusive",
    value: 7,
    cursedVal: 25,
    cursedAC: 20,
    ac: 4838,
    era: "???",
    releaseDate: "???",
    demand: "moderate",
},
{
    id: "39",
    name: "Glamrock Foxy",
    image: "/Skins/GlamrockFoxy.webp",
    tier: "exclusive",
    value: 2,
    ac: 4543,
    era: "???",
    releaseDate: "???",
    demand: "moderate",
},
{
    id: "40",
    cursedVal: 15,
    cursedAC: 20,
    name: "Bling Bonnie",
    image: "/Skins/BlingBonnie.webp",
    tier: "exclusive",
    value: 4,
    ac: 1306,
    era: "???",
    releaseDate: "???",
    demand: "moderate",
},
{   glitchedVal: 25,
    glitchedAC: 20,
    id: "42",
    name: "Loveshot Mangle",
    image: "/Skins/LoveShot.webp",
    tier: "exclusive",
    value: 2,
    cursedVal: 7,
    cursedAC: 20,
    ac: 3702,
    era: "Valentines",
    releaseDate: "???",
    demand: "moderate",
},
{
    id: "43",
    name: "Lava Marionette",
    image: "/Skins/LavaMarionette.webp",
    tier: "exclusive",
    cursedVal: 7,
    cursedAC: 20,
    value: 2,
    ac: 4253,
    era: "TJOC",
    releaseDate: "???",
    demand: "moderate",
},
{
    id: "44",
    name: "Krampus Burntrap",
    cursedVal: 7,
    cursedAC: 20,
    image: "/Skins/KrampusBurntrap.webp",
    tier: "exclusive",
    value: 2,
    ac: 5512,
    era: "Christmas",
    releaseDate: "???",
    demand: "moderate",
},
{
    id: "45",
    cursedVal: 15,
    cursedAC: 20,
    name: "Cardmaster Bonnie",
    image: "/Skins/CardmasterBonnie.webp",
    tier: "exclusive",
    value: 4,
    ac: 7354,
    era: "???",
    releaseDate: "???",
    demand: "moderate",
},
{
    id: "46",
    name: "Baker Freddy",
    image: "/Skins/BakerFreddy.webp",
    tier: "exclusive",
    value: 3,
    cursedVal: 10,
    cursedAC: 20,
    ac: 1157,
    era: "???",
    releaseDate: "???",
    demand: "moderate",
},
  {
    id: "47",
    name: "Ennard",
    image: "/Skins/Ennard.webp",
    tier: "sacred",
    updates: ["The ability now allows you to onetap anyone"],
    value: 1,
    ac: 9000,
    era: "???",
    releaseDate: "???",
    demand: "trending",
    cursedVal: 3,
    cursedAC: 100,
    glitchedVal: 18,
    glitchedAC: 100,
    gcVal: 60,
    gcAC: 10,
  },
  {
    id: "48",
    name: "Vanny",
    image: "/Skins/Vanny.webp",
    tier: "sacred",
    value: 1,
    ac: 8600,
    era: "???",
    releaseDate: "???",
    demand: "none",
    cursedVal: 3,
    cursedAC: 100,
    glitchedVal: 12,
    glitchedAC: 100,
    gcVal: 40,
    gcAC: 10,
  },
  {
    id: "49",
    name: "Lefty",
    image: "/Skins/Lefty.webp",
    tier: "sacred",
    value: 1,
    ac: 10000,
    era: "???",
    releaseDate: "???",
    demand: "none",
    cursedVal: 3,
    cursedAC: 100,
    glitchedVal: 10,
    glitchedAC: 100,
    gcVal: 35,
    gcAC: 10,
  },
  {
    id: "50",
    name: "Helpy",
    image: "/Skins/Helpy.webp",
    tier: "sacred",
    updates: ["With the release of ladybug helpy regular helpy isnt worth anything"],
    value: 1,
    ac: 10000,
    era: "???",
    releaseDate: "???",
    demand: "none",
    cursedVal: 3,
    cursedAC: 100,
    glitchedVal: 15,
    glitchedAC: 100,
    gcVal: 50,
    gcAC: 10,
  },
  {
    id: "51",
    name: "Purple Guy",
    image: "/Skins/PurpleGuy.webp",
    tier: "sacred",
    value: 1,
    ac: 10000,
    era: "???",
    releaseDate: "???",
    demand: "none",
    cursedVal: 3,
    cursedAC: 100,
    glitchedVal: 15,
    glitchedAC: 100,
    gcVal: 50,
    gcAC: 10,
  },
  {
    id: "52",
    name: "Scrapbaby",
    image: "/Skins/Scrapbaby.webp",
    tier: "sacred",
    value: 1,
    ac: 10000,
    era: "???",
    releaseDate: "???",
    demand: "none",
    cursedVal: 3,
    cursedAC: 100,
    glitchedVal: 10,
    glitchedAC: 100,
    gcVal: 35,
    gcAC: 10,
  },
  {
    id: "53",
    name: "Burntrap",
    image: "/Skins/Burntrap.webp",
    tier: "sacred",
    value: 1,
    ac: 10000,
    era: "???",
    releaseDate: "???",
    demand: "none",
    cursedVal: 3,
    cursedAC: 100,
    glitchedVal: 10,
    glitchedAC: 100,
    gcVal: 35,
    gcAC: 10,
  },
  {
    id: "54",
    name: "Nightmare Fredbear",
    image: "/Skins/NightmareFredbear.webp",
    tier: "sacred",
    value: 1,
    ac: 10000,
    era: "???",
    releaseDate: "???",
    demand: "none",
    cursedVal: 3,
    cursedAC: 100,
    glitchedVal: 10,
    glitchedAC: 100,
    gcVal: 35,
    gcAC: 10,
  },
  {
    id: "55",
    name: "Nightmare",
    image: "/Skins/Nightmare.webp",
    tier: "sacred",
    value: 1,
    ac: 10000,
    era: "???",
    releaseDate: "???",
    demand: "none",
    cursedVal: 3,
    cursedAC: 100,
    glitchedVal: 10,
    glitchedAC: 100,
    gcVal: 35,
    gcAC: 10,
  },
  {
    id: "56",
    name: "Moon",
    image: "/Skins/Moon.webp",
    tier: "sacred",
    value: 4,
    ac: 1259,
    era: "???",
    releaseDate: "???",
    demand: "moderate",
    cursedVal: 9,
    cursedAC: 30,
    glitchedVal: 30,
    glitchedAC: 30,
    gcVal: 100,
    gcAC: 1,
  },
  {
    id: "57",
    name: "Sun",
    image: "/Skins/Sun.webp",
    tier: "sacred",
    value: 3,
    ac: 1293,
    era: "???",
    releaseDate: "???",
    demand: "moderate",
    cursedVal: 9,
    cursedAC: 30,
    glitchedVal: 30,
    glitchedAC: 30,
    gcVal: 100,
    gcAC: 1,
  },
  {
    id: "58",
    name: "Mimic",
    image: "/Skins/Mimic.webp",
    tier: "sacred",
    value: 3,
    ac: 2007,
    era: "???",
    releaseDate: "???",
    demand: "moderate",
    cursedVal: 9,
    cursedAC: 30,
    glitchedVal: 30,
    glitchedAC: 30,
    gcVal: 100,
    gcAC: 1,
  },
  {
    id: "59",
    name: "Bubble Guy",
    image: "/Skins/BubbleGuy.webp",
    tier: "secret",
    value: 20,
    ac: 450,
    era: "???",
    releaseDate: "???",
    demand: "decent",
  },
  { 
    cursedVal: 12,
    cursedAC: 25,
    glitchedVal: 50,
    glitchedAC: 10,
    gcVal: 200,
    gcAC: 1,
    id: "60",
    name: "Shipwrecked",
    image: "/Skins/ShipWrecked.webp",
    tier: "sacred",
    value: 4,
    ac: 3000,
    era: "???",
    releaseDate: "???",
    demand: "trending",
  },
  {
    id: "61",
    name: "MXES",
    image: "/Skins/MXES.webp",
    tier: "sacred",
    value: 1,
    ac: 10000,
    era: "???",
    releaseDate: "???",
    demand: "none",
    cursedVal: 3,
    cursedAC: 100,
    glitchedVal: 10,
    glitchedAC: 100,
    gcVal: 35,
    gcAC: 10,
  },
]
